spring.application.name=examservice

spring.data.mongodb.uri=mongodb+srv://717822f144:Z5KxMLc4RovOD4Mx@cluster0.vpxgvw9.mongodb.net/utilitydb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=utilitydb

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.port=8080
